[package]
name = "rust_client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {version="4.1.13", features= ["derive"]}
itertools = "0.10.5"
priority-queue = "1.3.1"
rust_socketio = "0.4.1"
